### ISSUE TITLE
Incorrect import path

### ISSUE THREAD

**Issue by vincentmvdm** [drstearns/tutorials#4]
In the section [Tokenize the HTML](https://drstearns.github.io/tutorials/tokenizing/#sectokenizethehtml) the following import path is provided:

import (
    "fmt"
    "io"
    "log"
    "net/http"
    "os"
    "strings"

    "golang.org/x/net/html"
)

I am not sure if the code in the tutorial is supposed to be run before the section 'Refactor the Code', but if it is, the import path above will throw an error as "io" is not used. Only once the code is refactored and headers as "func extractTitle(body io.ReadCloser)" are used,  io should be imported.

**Comment by drstearns** [comment]
Good catch! I wrote my solution in the final, factored way, and then copied bits of it into the tutorial at a time, so that's why `io` is in the import path from the start. If you're using VSCode with the Go plugin, it should remove that import automatically, but I'll update the tutorial to make it correct.
